export type GameSystem = string;

export interface GM {
  id: string;
  name: string;
  avatar: string;
  bio: string;
  pronouns: string;
  yearsExperience: number;
  rating: number;
  reviewCount: number;
  pricePerSession: number;
  gamesHosted: number;
  timezone: string;
  languages: string[];
  identityTags: string[];
  systems: string[];
  themes: string[];
  platforms: string[];
  highlights: string[];
  responseTime: string;
  responseRate: string;
  yearsOnPlatform: number;
  social: { twitch?: string; youtube?: string; twitter?: string; instagram?: string };
}

export interface Game {
  id: string;
  title: string;
  system: GameSystem;
  gm: GM;
  dateTime: string;
  totalSeats: number;
  seatsAvailable: number;
  pricePerSession: number;
  shortDescription: string;
  fullDescription: string;
  tags: string[];
  duration: string;
}

export const GMS: GM[] = [
  {
    id: "gm1",
    name: "Allison (Ajax DM)",
    avatar: "AA",
    pronouns: "she/her",
    bio: "Ajax DM is a full-time professional DM with 54 completed multi-year campaigns, over 3,000 sessions (in-person and online) — including 1,800+ on StartPlaying — and 11,000+ hours on Roll20 (since March, 2020).\n\nAjax DM offers paid weekly games you can count on. Weekly 3-hour D&D 5e game sessions on Roll20 or Alchemy RPG, using official D&D 5e campaign materials supplemented with additional colour maps, extra tokens, 3D dice rolling, Dynamic Lighting, and sourcebook/compendium sharing. New or experienced players and those just coming back to D&D are welcome — you'll learn as you play.\n\nAllison was honored to be selected to DM at Gen Con 2024 independently, with Limithron (Pirate Borg) in 2024, for StartPlaying at Gen Con in 2023, and for Kobold Press at Gen Con in both 2022 and 2023.",
    yearsExperience: 6,
    rating: 5,
    reviewCount: 135,
    pricePerSession: 40,
    gamesHosted: 1860,
    timezone: "America/New_York",
    languages: ["English", "Italian"],
    identityTags: ["Women/Femme Identifying", "Multi-lingual", "Convention GM"],
    systems: ["D&D 5e", "Kids on Bikes", "Vaesen", "Pirate Borg", "Candela Obscura"],
    themes: ["Fantasy", "Adventure", "Horror", "New Player Friendly"],
    platforms: ["Roll20", "Alchemy RPG", "Discord"],
    highlights: ["Inclusive", "Teacher", "Creativity"],
    responseTime: "Under 1 hour",
    responseRate: "99%",
    yearsOnPlatform: 5,
    social: {},
  },
  {
    id: "gm2",
    name: "X Da Storyteller",
    avatar: "XS",
    pronouns: "any/all",
    bio: "Roleplay is always going to be a huge part of my games, and I strive to give each NPC a unique voice and supply them with their own motivations and agendas, and just generally try to make the world feel consistent and immersive.\n\nI use music to set the mood and tone of any given or particular scene, and strive for atmosphere. Combat tends to be violent, quick, and deadly in my games. The narrative context of a given fight matters more to me than balance, so players are encouraged to be selective about which battles they choose to engage in — I feel it would be disingenuous to the experience if I made the world pull its punches.",
    yearsExperience: 4,
    rating: 5,
    reviewCount: 22,
    pricePerSession: 20,
    gamesHosted: 409,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["LGBTQ+", "Queer", "BIMPOC", "Black", "Neurodivergent", "Voice Actor"],
    systems: ["Kids on Bikes", "Vampire: The Masquerade", "Cyberpunk Red", "Werewolf: The Apocalypse"],
    themes: ["Horror", "Urban Fantasy", "Cyberpunk", "Character Drama", "Atmosphere"],
    platforms: ["Roll20", "Discord", "Foundry VTT"],
    highlights: ["Storytelling", "Creativity", "Inclusive"],
    responseTime: "Under 2 hours",
    responseRate: "100%",
    yearsOnPlatform: 2,
    social: {},
  },
  {
    id: "gm3",
    name: "Tim",
    avatar: "TI",
    pronouns: "he/him",
    bio: "I have been DMing for several years, and, quite simply, I love the game. I love building a story together with others. I love doing the voices of a million NPCs. I love the dumb jokes that just sort of happen around the table.\n\nOutside of gaming, I am a professional actor. My background is in improv and sketch comedy. So taking on a variety of different, interesting characters IS my wheelhouse. Let's get together and make something excellent happen.",
    yearsExperience: 5,
    rating: 5,
    reviewCount: 22,
    pricePerSession: 20,
    gamesHosted: 140,
    timezone: "America/Los_Angeles",
    languages: ["English"],
    identityTags: ["Improv Trained", "Professional Actor"],
    systems: ["D&D 5e"],
    themes: ["Fantasy", "Comedy", "Character Drama", "Adventure"],
    platforms: ["Roll20", "Discord"],
    highlights: ["Voices", "Storytelling", "Creativity"],
    responseTime: "Under 3 hours",
    responseRate: "97%",
    yearsOnPlatform: 2,
    social: {},
  },
  {
    id: "gm4",
    name: "David (The avidDM)",
    avatar: "DA",
    pronouns: "he/him",
    bio: "Over the last four years, I have met hundreds of incredible people around the virtual table. The stories we've shared have brought joy, laughter, and even a few tears into our lives. Many of these folks return to the table year after year.\n\nMy road to becoming a professional Dungeon Master began with a few little fibs I used to tell as an extremely shy kid. When I met new people, I would tell them cowboy stories about adventures I had with my faithful steed. Growing up in the Midwest, D&D was all around me. Fast forward to 2016 — I opened up the Lost Mines of Phandelver Box Set, and after a 25-year hiatus from the hobby I loved, I sat down with my kids and rediscovered the joy of Tabletop Role-Playing Games. Grab a seat, roll some dice, live the adventure.",
    yearsExperience: 5,
    rating: 5,
    reviewCount: 132,
    pricePerSession: 35,
    gamesHosted: 1071,
    timezone: "America/Chicago",
    languages: ["English"],
    identityTags: ["Convention GM"],
    systems: ["D&D 5e", "Alien: The Roleplaying Game", "Marvel Multiverse RPG", "Daggerheart"],
    themes: ["Fantasy", "Adventure", "Sci-Fi", "Superhero", "New Player Friendly"],
    platforms: ["Roll20", "Foundry VTT", "Discord"],
    highlights: ["Teacher", "Creativity", "Knows the Rules"],
    responseTime: "Under 2 hours",
    responseRate: "98%",
    yearsOnPlatform: 4,
    social: {},
  },
  {
    id: "gm5",
    name: "Don",
    avatar: "DO",
    pronouns: "he/him",
    bio: "I love it when a group comes together to interactively create a fantastical, fun, memorable story. I've just wrapped my 3rd full 5e campaign and cherish that bittersweet moment after the epilogue where you sign off for the last time.\n\nSetting the stage is my role and I dive in with gusto (and humour). You work with the other players to drive the story forward. I'll also weave your backstory into the plot so your character has some time in a spotlight. Oh, and if we aren't laughing our butts off periodically, we are definitely doing something wrong. I have players who joined me early in the pandemic and are still gaming with me now.",
    yearsExperience: 5,
    rating: 5,
    reviewCount: 6,
    pricePerSession: 20,
    gamesHosted: 10,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["Neurodivergent", "Canadian"],
    systems: ["D&D 5e"],
    themes: ["Fantasy", "Character Drama", "Comedy", "Adventure"],
    platforms: ["Roll20", "Discord"],
    highlights: ["Inclusive", "Storytelling", "Creativity"],
    responseTime: "Under 4 hours",
    responseRate: "95%",
    yearsOnPlatform: 1,
    social: {},
  },
  {
    id: "gm6",
    name: "James",
    avatar: "JA",
    pronouns: "he/him",
    bio: "James is one of the best GMs many players have had the pleasure of playing with. His incredible storytelling matches perfectly with the amazing environments he creates. In mystery-focused campaigns, the environments and tensions are nail-biting with so much freedom on what to do.\n\nJames is amazing with player freedom as well, doing as much as possible to mesh the story with the character you want to create. Combat is always dynamic — enemies react intelligently, creating genuinely surprising tactical situations. He is a stellar GM who is especially recommended for Pathfinder.",
    yearsExperience: 8,
    rating: 5,
    reviewCount: 70,
    pricePerSession: 40,
    gamesHosted: 704,
    timezone: "America/Los_Angeles",
    languages: ["English"],
    identityTags: ["Convention GM"],
    systems: ["Pathfinder 2e", "Call of Cthulhu", "Warhammer Fantasy Roleplay", "Delta Green", "Traveller"],
    themes: ["Mystery", "Investigation", "Horror", "Sci-Fi", "Fantasy"],
    platforms: ["Foundry VTT", "Roll20", "Discord"],
    highlights: ["Storytelling", "Teacher", "Creativity"],
    responseTime: "Under 2 hours",
    responseRate: "99%",
    yearsOnPlatform: 3,
    social: {},
  },
  {
    id: "gm7",
    name: "John",
    avatar: "JO",
    pronouns: "he/him",
    bio: "I host high-value games featuring great acting, player choice, deep roleplay, tactical complexity, immersive media, and high tech. I have 15+ years of acting and public speaking experience, 20+ years of world-building, and 11+ years running D&D 5e.\n\nMy secret sauce: a nice voice, a fantasy-prone brain, and blending high tech with great acting. Expect a fully voice-acted cast of characters, immersive soundscapes, custom world-building, and lots of pretty scenes. I've driven a puppy-powered dog-sled atop an Alaskan glacier and once sang at Carnegie Hall — and somehow, GMing is still the most fun I've had.",
    yearsExperience: 11,
    rating: 5,
    reviewCount: 82,
    pricePerSession: 40,
    gamesHosted: 588,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["Voice Actor", "Theater Trained"],
    systems: ["D&D 5e", "Pathfinder 2e", "Blades in the Dark", "Lancer", "Stars Without Number"],
    themes: ["Fantasy", "Sci-Fi", "Urban Fantasy", "Heist", "Character Drama"],
    platforms: ["Foundry VTT", "Roll20", "Discord"],
    highlights: ["Storytelling", "Sets the Mood", "World Builder"],
    responseTime: "Under 1 hour",
    responseRate: "100%",
    yearsOnPlatform: 3,
    social: {},
  },
  {
    id: "gm8",
    name: "Kobold DM",
    avatar: "KD",
    pronouns: "he/him",
    bio: "Not only is Kobold a fun and engaging DM, but he does a phenomenal job at immersing you into the world he has created while simultaneously inviting players to experiment with fun character ideas.\n\nWhether you are someone new or experienced, you can rest assured that Kobold will provide you with a DM experience that far exceeds expectations. He excels at incredible visual aids, allowing player creativity, the rule of cool, knowing the rules, world-building, and setting the mood with soundscapes and music. Give him a shot and you won't regret it.",
    yearsExperience: 5,
    rating: 5,
    reviewCount: 39,
    pricePerSession: 30,
    gamesHosted: 220,
    timezone: "America/Chicago",
    languages: ["English"],
    identityTags: [],
    systems: ["Pathfinder 2e"],
    themes: ["Fantasy", "Tactical Combat", "World Building", "Adventure"],
    platforms: ["Foundry VTT", "Discord"],
    highlights: ["Teacher", "Knows the Rules", "Creativity"],
    responseTime: "Under 3 hours",
    responseRate: "96%",
    yearsOnPlatform: 2,
    social: {},
  },
  {
    id: "gm9",
    name: "DM Deadman",
    avatar: "DD",
    pronouns: "he/him",
    bio: "As someone who came to the hobby after a 30-year, 3-edition hiatus, I cannot recommend Deadman enough. He runs fun and wildly entertaining campaigns and is patient and helpful for newcomers who need some handholding before feeling like they know what they're doing.\n\nHe does a plethora of great voices for characters and races, is quick to laugh when players want to make jokes, and is willing to veer slightly off the plan if the story makes sense. Extremely helpful between sessions and willing to work with you on things you may want or are curious about. Also has some really good homebrew rules that make a lot of sense.",
    yearsExperience: 4,
    rating: 5,
    reviewCount: 12,
    pricePerSession: 30,
    gamesHosted: 180,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: [],
    systems: ["D&D 5e", "Call of Cthulhu"],
    themes: ["Fantasy", "Horror", "Atmosphere", "Comedy"],
    platforms: ["Roll20", "Discord"],
    highlights: ["Creativity", "Sets the Mood", "Voices"],
    responseTime: "Under 4 hours",
    responseRate: "94%",
    yearsOnPlatform: 2,
    social: {},
  },
  {
    id: "gm10",
    name: "Heartlock",
    avatar: "HL",
    pronouns: "he/him",
    bio: "Despite having played and DMed D&D for 40 years, this is my first experience running online games. I wasn't familiar with the technology aspect but I make sure players feel welcome and comfortable with it. I am a very good storyteller.\n\n12 or so sessions in, despite using a pre-written campaign, players feel their characters have been able to grow and explore without being herded. When players do things clearly not counted on, I do well off-the-cuff without losing sight of the story. There is very good flow to every story — never a feeling of being stuck.",
    yearsExperience: 40,
    rating: 5,
    reviewCount: 9,
    pricePerSession: 25,
    gamesHosted: 237,
    timezone: "America/Chicago",
    languages: ["English"],
    identityTags: ["Neurodivergent", "Voice Actor"],
    systems: ["D&D 5e", "Monster of the Week", "Marvel Multiverse RPG"],
    themes: ["Fantasy", "Superhero", "Horror", "Character Drama"],
    platforms: ["Roll20", "Discord"],
    highlights: ["Storytelling", "Creativity", "Inclusive"],
    responseTime: "Under 3 hours",
    responseRate: "97%",
    yearsOnPlatform: 1,
    social: {},
  },
  {
    id: "gm11",
    name: "Louis G.",
    avatar: "LG",
    pronouns: "he/they",
    bio: "Louis has been playing and DMing Dungeons and Dragons for 4 years. His style leans heavily towards roleplay, but he also likes to run tactical battles where enemies are smart and coordinated to challenge his players and encourage them to push the limits of their abilities.\n\nLouis is a sketch comedy writer and voice actor, and he loves to build his worlds with engaging NPCs. He strives to create a unique voice and personality for everyone the party interacts with. Games are mostly run via AboveVTT and Discord. Priority order: 1) Roleplay, 2) Combat, 3) Exploration, 4) Political Intrigue.",
    yearsExperience: 4,
    rating: 5,
    reviewCount: 52,
    pricePerSession: 35,
    gamesHosted: 310,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["Voice Actor", "Comedy Writer"],
    systems: ["D&D 5e", "Monster of the Week"],
    themes: ["Fantasy", "Horror", "Political Intrigue", "Comedy"],
    platforms: ["AboveVTT", "Discord"],
    highlights: ["Creativity", "Voices", "Storytelling"],
    responseTime: "Under 2 hours",
    responseRate: "98%",
    yearsOnPlatform: 2,
    social: {},
  },
  {
    id: "gm12",
    name: "Prism DM",
    avatar: "PD",
    pronouns: "he/him",
    bio: "I have been a DM for close to a decade, but in a roundabout way it took me a few years to find D&D. I rolled with a group that was too cool to play something as 'mainstream' as D&D — sad to think I spent so long in FATE to appease them! Now I've been my own DM for about five years, running Pathfinder 1e and D&D 5e in campaigns both prewritten and homebrewed.\n\nYou deserve my time and attention, much as I expect the same from my players in return. I really put everything I have into my campaigns — crafting custom encounter maps, reviewing and rebuilding adventures, and jury-rigging complex VTT interactions to run as smoothly as possible with automation and user-friendly interfaces that work for you.",
    yearsExperience: 9,
    rating: 5,
    reviewCount: 69,
    pricePerSession: 0,
    gamesHosted: 717,
    timezone: "America/Chicago",
    languages: ["English"],
    identityTags: ["LGBTQ+"],
    systems: ["D&D 5e", "Pathfinder 1e"],
    themes: ["Fantasy", "Tactical Combat", "World Building", "Adventure"],
    platforms: ["Foundry VTT", "Roll20", "Discord"],
    highlights: ["Knows the Rules", "Sets the Mood", "Visual Aid"],
    responseTime: "Under 2 hours",
    responseRate: "99%",
    yearsOnPlatform: 3,
    social: {},
  },
  {
    id: "gm13",
    name: "shevek1312",
    avatar: "SH",
    pronouns: "they/them",
    bio: "Tabletop games are collaborative storytelling — this means you get out what you put in. Our tables actively seek out RP scenes with one another or NPCs, internal monologues, and out-of-session banter. Interaction is exposition.\n\nConflict can drive a story, but the relationships are what's at the core of those conflicts. I run a huge range of systems — from D&D and Call of Cthulhu to Avatar Legends, Blades in the Dark, Blade Runner, and over two dozen more. Combat is the part I'm least interested in simulating through improvisational storytelling, so I need the game to handle that while I take care of emotions, relationships, and character progression.",
    yearsExperience: 7,
    rating: 5,
    reviewCount: 54,
    pricePerSession: 40,
    gamesHosted: 350,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["Queer", "Disabled", "Neurodivergent", "Voice Actor", "LGBTQ+"],
    systems: ["D&D 5e", "Call of Cthulhu", "Vampire: The Masquerade", "Blades in the Dark", "Alien RPG", "Avatar Legends", "Blade Runner RPG"],
    themes: ["Horror", "Sci-Fi", "Fantasy", "Character Drama", "Inclusive"],
    platforms: ["Foundry VTT", "Roll20", "Discord"],
    highlights: ["Creativity", "Storytelling", "Inclusive"],
    responseTime: "Under 3 hours",
    responseRate: "97%",
    yearsOnPlatform: 2,
    social: {},
  },
  {
    id: "gm14",
    name: "ArcaneBenji",
    avatar: "AB",
    pronouns: "he/him",
    bio: "Before I've played with Ben, I was new to DnD and had one campaign under my belt. With Ben's help and patience I seemed to learn even more, and not only that — he really takes the time to build a visual world which is huge for really feeling like you're diving into great RP.\n\nHe lets players voice opinions on ideas and literally lets players dictate what happens next by being open to all crazy ideas, while always keeping on track of plot points. Each session feels like a story plot twist you never saw coming. He really tries to make sure players are having fun in anything and everything, so thanks Ben for all the games — I highly recommend him to all.",
    yearsExperience: 5,
    rating: 4.9,
    reviewCount: 42,
    pricePerSession: 25,
    gamesHosted: 607,
    timezone: "America/Chicago",
    languages: ["English"],
    identityTags: ["Neurodivergent"],
    systems: ["D&D 5e", "Pathfinder 2e", "Lancer"],
    themes: ["Fantasy", "Sci-Fi", "World Building", "Adventure"],
    platforms: ["Roll20", "Foundry VTT", "Discord"],
    highlights: ["Creativity", "Teacher", "World Builder"],
    responseTime: "Under 2 hours",
    responseRate: "98%",
    yearsOnPlatform: 3,
    social: {},
  },
  {
    id: "gm15",
    name: "Byrne Baby Byrne",
    avatar: "BB",
    pronouns: "she/her",
    bio: "I work hard to make my games as safe and inclusive as possible. I've had the experience of being The Only Girl at the Table — in a game featuring vampires, I've been told I can't play a warrior because it's 'not realistic.' It's my goal to make my games the EXACT OPPOSITE of those experiences by creating an environment where marginalized players can be themselves and see themselves in the games they play.\n\nI started playing Vampire: The Masquerade when I was only 13 years old and ran my first VtM game shortly after. I've been both player and storyteller for Werewolf, Changeling, Hunter, and Wraith — with a little D&D and Monster of the Week sprinkled in for good measure. I'm also a lifelong horror fan.",
    yearsExperience: 15,
    rating: 4.9,
    reviewCount: 117,
    pricePerSession: 50,
    gamesHosted: 2073,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["LGBTQ+", "Neurodivergent", "Women/Femme Identifying", "Safety Tool Advocate"],
    systems: ["Vampire: The Masquerade", "Monster of the Week", "Werewolf: The Apocalypse", "Hunter: The Reckoning", "Changeling: The Dreaming"],
    themes: ["Gothic Horror", "Urban Fantasy", "Character Drama", "Inclusive", "Psychological Horror"],
    platforms: ["Roll20", "Discord"],
    highlights: ["Storytelling", "Inclusive", "Creativity"],
    responseTime: "Under 2 hours",
    responseRate: "99%",
    yearsOnPlatform: 5,
    social: { instagram: "byrne_baby_byrne" },
  },
  {
    id: "gm16",
    name: "Felipe Lopez",
    avatar: "FL",
    pronouns: "he/they",
    bio: "Felipe helped me learn how to play Tabletop RPGs with patience and humor. He is especially good for new players but keeps things interesting for veterans as well. He has created an entire homebrew setting called Irhafel, complete with custom magic items, homebrew races, and classes — a staggering level of detail and immersion.\n\nFelipe keeps combat moving and engaging, has tons of maps and tricks to make exploration feel genuinely scary and surprising, and brings a wide cast of NPCs into the roleplay. He also manages inter-player dynamics with impressive emotional intelligence to make sure everyone is having fun.",
    yearsExperience: 6,
    rating: 5,
    reviewCount: 22,
    pricePerSession: 20,
    gamesHosted: 755,
    timezone: "America/Sao_Paulo",
    languages: ["English", "Portuguese"],
    identityTags: ["LGBTQ+", "Queer", "Multi-lingual"],
    systems: ["D&D 5e", "Call of Cthulhu", "Fate Core", "Cypher System", "Paranoia"],
    themes: ["Fantasy", "Horror", "Character Drama", "Investigation", "Comedy"],
    platforms: ["Roll20", "Discord"],
    highlights: ["Inclusive", "Creativity", "Teacher"],
    responseTime: "Under 3 hours",
    responseRate: "96%",
    yearsOnPlatform: 3,
    social: {},
  },
  {
    id: "gm17",
    name: "Fitz",
    avatar: "FI",
    pronouns: "he/him",
    bio: "Fitz is the best GM I have ever had the pleasure to play with. Hard stop. His world-building is incredibly thought out, and players are constantly on their toes in the best way. From day one, Fitz worked tirelessly to create player backstory engagement, and you can clearly see how player actions impact the direction the story goes.\n\nThe scenarios are challenging but very balanced and fair, and player creativity and strategy is both necessary and rewarded. The story NEVER feels like Player vs. GM. Instead, Fitz creates an atmosphere where everyone — GM included — is striving towards similar goals. Fitz is VERY accommodating for beginners, but the story and world really benefit from active player roleplay.",
    yearsExperience: 5,
    rating: 5,
    reviewCount: 11,
    pricePerSession: 15,
    gamesHosted: 90,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["Veteran"],
    systems: ["D&D 5e"],
    themes: ["Fantasy", "World Building", "Character Drama", "Adventure"],
    platforms: ["Roll20", "Discord"],
    highlights: ["Storytelling", "Creativity", "World Builder"],
    responseTime: "Under 4 hours",
    responseRate: "95%",
    yearsOnPlatform: 1,
    social: {},
  },
  {
    id: "gm18",
    name: "Cabe",
    avatar: "CA",
    pronouns: "he/him",
    bio: "I've been playing TTRPGs and roleplaying in general for many years, so it's safe to say I've learned a great deal. I am fun-centered, story driven, and a firm believer in the rule of cool. I will always take the players' preferences for combat, exploration, and roleplaying into account — but above all I want to tell a story with you.\n\nI run predominantly homebrew campaigns and I can help balance ideas for custom content as well. Feel free to ask about any game system you'd like to play, because I'm open to anything.",
    yearsExperience: 6,
    rating: 5,
    reviewCount: 29,
    pricePerSession: 25,
    gamesHosted: 280,
    timezone: "America/Indiana/Indianapolis",
    languages: ["English"],
    identityTags: ["LGBTQ+", "Neurodivergent", "Voice Actor"],
    systems: ["D&D 5e", "Pathfinder 2e", "Call of Cthulhu", "Cyberpunk Red", "Candela Obscura"],
    themes: ["Fantasy", "Horror", "Cyberpunk", "World Building", "Adventure"],
    platforms: ["Foundry VTT", "Roll20", "Discord"],
    highlights: ["Storytelling", "Creativity", "World Builder"],
    responseTime: "Under 2 hours",
    responseRate: "98%",
    yearsOnPlatform: 2,
    social: {},
  },
  {
    id: "gm19",
    name: "GloriousGe0rge",
    avatar: "GG",
    pronouns: "he/him",
    bio: "Hi all! My name is George, I am a Dungeon Master and Storyteller with over 10 years of experience running games professionally for places like Forgotten Adventures, where I currently stream my games twice a week! I have also run games professionally for corporate clients and events.\n\nI have experience running Dungeons & Dragons 5e, Mothership, Call of Cthulhu, Vampire the Masquerade, Hunter the Reckoning, Cyberpunk, and Kids on Bikes. My goal is to make enough money running games to focus on this full time — and I'm also open to offers or requests if you need a game at a different time.",
    yearsExperience: 10,
    rating: 5,
    reviewCount: 16,
    pricePerSession: 20,
    gamesHosted: 78,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["Neurodivergent", "Voice Actor", "Streamer"],
    systems: ["D&D 5e", "Mothership", "Call of Cthulhu", "Vampire: The Masquerade", "Hunter: The Reckoning"],
    themes: ["Horror", "Fantasy", "Sci-Fi", "Urban Fantasy", "Atmosphere"],
    platforms: ["Roll20", "Foundry VTT", "Discord"],
    highlights: ["Storytelling", "Visual Aid", "Voices"],
    responseTime: "Under 2 hours",
    responseRate: "97%",
    yearsOnPlatform: 1,
    social: {},
  },
  {
    id: "gm20",
    name: "Jake Ware",
    avatar: "JW",
    pronouns: "he/him",
    bio: "Back in the day, I played AD&D every Sunday at noon. I had never really been friends with the DMs — two brothers who took turns. We played until dinner. We were into it. I played Felris Quickfingers, Svirfneblin Jester.\n\nI started social groups using DnD and Pathfinder in a middle school, teaching kids D&D and building relationships that way. Eventually I switched to playing with friends and family during the pandemic. Now I DM almost exclusively. I foolishly thought I would DM to inspire my players to also become DMs. In the meantime, I discovered I love the range of creativity this hobby brings out in us all, and all the ways it brings people together.",
    yearsExperience: 7,
    rating: 5,
    reviewCount: 73,
    pricePerSession: 25,
    gamesHosted: 432,
    timezone: "America/New_York",
    languages: ["English"],
    identityTags: ["Former Educator"],
    systems: ["D&D 5e", "Pathfinder 2e", "Kids on Bikes", "Daggerheart", "Dolmenwood", "Draw Steel"],
    themes: ["Fantasy", "Adventure", "Old School", "Character Drama", "New Player Friendly"],
    platforms: ["Foundry VTT", "Roll20", "Discord"],
    highlights: ["Creativity", "Teacher", "Knows the Rules"],
    responseTime: "Under 3 hours",
    responseRate: "96%",
    yearsOnPlatform: 2,
    social: {},
  },
];

export const GAMES: Game[] = [
  {
    id: "g1",
    title: "Ocarina of Time – Master Quest Legend of Zelda 5e",
    system: "D&D 5e",
    gm: GMS[0],
    dateTime: "2026-04-22T18:00:00",
    totalSeats: 5,
    seatsAvailable: 1,
    pricePerSession: 16,
    shortDescription: "A homebrew D&D 5e campaign adapting the beloved Legend of Zelda: Ocarina of Time into tabletop form — with improv-driven storytelling and unorthodox adventure.",
    fullDescription: "I have been hosting tabletop games for over 5 years and have experience DMing all walks of life. I also have over 10 years of improv experience as well as a fan of fiction writing.\n\nI tend to run games that are unorthodox — such as this Ocarina of Time campaign and an NCIS-style cop drama set in 80s Miami. I try to take the system into wild places but with well-crafted writing and fun action to go along with it. I'm more 60/40 RP being more of the front runner, but I try to make sure there's a good balance of combat and storytelling.",
    tags: ["Homebrew", "Video Game Adaptation", "Improv", "Adventure"],
    duration: "3 hours",
  },
  {
    id: "g2",
    title: "Descent Into Avernus – Level 1–12",
    system: "D&D 5e",
    gm: GMS[1],
    dateTime: "2026-04-23T19:00:00",
    totalSeats: 4,
    seatsAvailable: 1,
    pricePerSession: 20,
    shortDescription: "Baldur's Gate teeters on the edge of madness. Dive into the Nine Hells in this ongoing campaign — currently 9 sessions in, party of 3, looking to fill the roster.",
    fullDescription: "This campaign is nine sessions in, with a party of a bard, fighter and cleric. Originally a party of six, scheduling conflicts and personal lives have caused a tumultuous recruitment. I am looking to refill the party again to continue the adventure into Avernus.\n\nThe party has just finished clearing out the Dungeon of the Dead Three. Current level is three, with a solid cast all ready to dive into the hells.\n\nThe Path to Redemption is Paved with Hellfire. Baldur's Gate faces an uncertain future. Crime festers in its streets, corruption rules its leaders, and a sinister shadow looms over its people. In Avernus — the first layer of the Nine Hells — the remnants of a celestial war rage on. Your party will face fiendish enemies, navigate a realm consumed by fire and ash, and make choices that could save or condemn their souls. Hell awaits.",
    tags: ["Ongoing Campaign", "Hell", "Moral Choices", "Published Adventure"],
    duration: "3.5 hours",
  },
  {
    id: "g3",
    title: "Into the Pirate Haven | Beginner Friendly",
    system: "D&D 5e",
    gm: GMS[2],
    dateTime: "2026-04-24T14:00:00",
    totalSeats: 4,
    seatsAvailable: 2,
    pricePerSession: 15,
    shortDescription: "A beginner-friendly swashbuckling adventure from a long-time DM with roots going back to '83, bringing decades of storytelling experience to the virtual table.",
    fullDescription: "I'm a long-time DM, starting back in '83, and have played and run a variety of systems, including GURPS, Star Frontiers, Call of Cthulhu, TMNT/Rifts, and a bunch of others, but my focus has been D&D, from Basic to 5.5.\n\nI've been in the education industry since the early 90s, and taught for almost two decades. For the last twenty-odd years, I've been an editor at the family educational simulation company. I've written several books and edited a few anthologies. My work tends to be character-focused as well as grounded in history and science.\n\nThis pirate adventure is designed to be accessible to new players while still delivering satisfying challenges and a rich setting.",
    tags: ["Beginner Friendly", "Pirates", "Swashbuckling", "New Player Friendly"],
    duration: "3 hours",
  },
  {
    id: "g4",
    title: "Dungeons of Drakkenheim – New Campaign",
    system: "D&D 5e",
    gm: GMS[3],
    dateTime: "2026-04-25T19:00:00",
    totalSeats: 5,
    seatsAvailable: 3,
    pricePerSession: 20,
    shortDescription: "Dive into a ruined city suffused with eldritch magic. Cake blends fantasy, horror, and humor into handcrafted campaigns where shared storytelling takes center stage.",
    fullDescription: "Greetings, I'm Cake! I'm your easy-going facilitator of both in-person and online quests in Dungeons and Dragons 5e, Daggerheart, and Call of Cthulhu. I've been a storyteller my whole life, but about six years ago I fell in love with the TTRPG medium and I haven't looked back!\n\nThe art of creating adventures and crafting tales has captivated me since my childhood, and now that I've found TTRPGs, these wild ideas have been evolving into handcrafted memorable campaigns. I like to blend fantasy, horror, and humor into a few hours of gaming where we can just sink into our characters and the scenes.\n\nShared storytelling is one of my favorite things about TTRPGs — as a DM, I set up the world and you knock it down, sometimes literally. Join me on our collective journey through thrilling escapades, where laughter, challenges, and unforeseen surprises await.",
    tags: ["Horror", "Fantasy", "Humor", "New Campaign"],
    duration: "3.5 hours",
  },
  {
    id: "g5",
    title: "Legends of Night City: Cyberpunk Red",
    system: "Cyberpunk Red",
    gm: GMS[4],
    dateTime: "2026-04-26T20:00:00",
    totalSeats: 5,
    seatsAvailable: 1,
    pricePerSession: 20,
    shortDescription: "You don't make a name as an Edgerunner by how you live — you make it by how you die. Fight to survive in Night City against gangs, nomad bikers, and evil corporations.",
    fullDescription: "You Don't Make a name for yourself as an Edgerunner by how you live Choom... you make a name by how you die. The question is how do you wanna go out? In a Blaze of Glory under a Neon Sky, or hidden up in a dark hole somewhere?\n\nJoin the millions of denizens of Night City. Etch a name out in history with bullets and Rock Music. Fight to survive against Gangs, Nomad Bikers, and Evil Corporations. Equip yourself with Chrome Cyberware and the latest weapon your Fixer can find.\n\nBuild your Rep and become a legend. Night City is full of Twists, Turns, and Chaos around every corner. Whether you are a seasoned Vet or a complete Beginner this game is for you. This is an Episodic Homebrewed Campaign — everything your characters do impacts the world for campaigns to come. You become the Lore. Combat/Roleplay 50%/50% split.",
    tags: ["Cyberpunk", "Episodic", "Homebrew", "Beginner Friendly"],
    duration: "3.5 hours",
  },
  {
    id: "g6",
    title: "Legends of Luxor – Original Campaign Level 1–15",
    system: "D&D 5e",
    gm: GMS[5],
    dateTime: "2026-04-27T13:00:00",
    totalSeats: 5,
    seatsAvailable: 1,
    pricePerSession: 20,
    shortDescription: "A richly fleshed-out homebrew world where the jealous god Morthos once plunged civilisation into darkness. Free Session 0 included.",
    fullDescription: "Hundreds of years ago, the jealous god Morthos plunged the world into a dark 'Twilight Age.' A brave group of adventurers cast one grand spell to seal the dark god away. Since then, the world has flourished — but at this year's grand gladiatorial festival, the king is nowhere to be seen.\n\nAfter having 5 groups run through this world, it is more alive and fleshed out than ever. This is a beginner and advanced player friendly original campaign. It is relatively high fantasy, jumping genres and seeing the party charge magical artifacts all around the kingdom. Combat happens relatively often, and can be challenging but fair. Major points always go to parties who come up with creative solutions.\n\nAll party members will be asked about a personal character journey they want to take in Session 0. I want to make sure we get to explore each character and see them grow.",
    tags: ["Homebrew", "Original World", "Long Campaign", "Free Session 0"],
    duration: "4 hours",
  },
  {
    id: "g7",
    title: "The Wild Beyond the Witchlight [lvl 1–8, FREE Session 0]",
    system: "D&D 5e",
    gm: GMS[6],
    dateTime: "2026-04-27T19:00:00",
    totalSeats: 5,
    seatsAvailable: 4,
    pricePerSession: 30,
    shortDescription: "A whimsical D&D adventure through a magical carnival and the Feywild — with free Session 0, custom character art drawn by the GM, and immersive soundscapes.",
    fullDescription: "When you play with me, you receive: a GM with a deep understanding of 5e rules who will help familiarize you with the game in a judgment-free environment; a bespoke game complete with immersive roleplay, music, and art; dynamic combat where players are encouraged to think outside the box; and unique, custom-made art of your character, created by the GM.\n\nBefore our first true session, I will host a free Session 0 to help players develop their characters and build their character sheets — covering not only mechanical elements, but also strategies to help think of backstories and goals.\n\nI also provide committed players with unique custom character art (no AI used). These pieces are full body, full color depictions based on players' descriptions. Each piece is a $60 value, offered free to anyone who attends three or more sessions.",
    tags: ["Feywild", "Whimsical", "Custom Art", "Free Session 0", "New Player Friendly"],
    duration: "3.5 hours",
  },
  {
    id: "g8",
    title: "Dolmenwood: Of Mushrooms & Mandrake Root",
    system: "Old-School Essentials",
    gm: GMS[7],
    dateTime: "2026-04-28T15:00:00",
    totalSeats: 5,
    seatsAvailable: 3,
    pricePerSession: 20,
    shortDescription: "Eccentric fairies, craven pirates, and poignant dragons await in this old-school fairy tale RPG. Over 28 years of GM experience, with a 2022 Goodie Award to show for it.",
    fullDescription: "Over 28 years of running roleplaying games, I've collected amazing stories as a game master for friends, family, and people I connected with online, in stores, and at conventions.\n\nMy goal is to strike a chord in you that you forgot was there. To evoke your barely remembered dreams and memories. I strive to run your dream game — an immersive game that puts you in the moment, where you can exercise your imagination and make real choices.\n\nIn my games, the fairies are eccentric, the pirates are craven, the dragons poignant and monstrous in turn. The battles are death-defying while the gardens hide secrets just out of sight, and the dungeons make you question reality as you explore them. I've run over 100 different published adventures, in addition to homebrewed campaigns. I wrote a zine-length fairy tale roleplaying game called 'In the Court of the Fairy Queen' and am a recipient of the 2022 Goodie Award presented by Goodman Games.",
    tags: ["Old School", "Fairy Tale", "Award-Winning GM", "Atmosphere"],
    duration: "3 hours",
  },
  {
    id: "g9",
    title: "Carnage in the Cascades",
    system: "Deadlands",
    gm: GMS[8],
    dateTime: "2026-04-28T20:00:00",
    totalSeats: 5,
    seatsAvailable: 1,
    pricePerSession: 23,
    shortDescription: "A Savage Worlds Deadlands adventure set in the weird west. JJ is incredibly knowledgeable, patient, and has introduced players to multiple systems — a friend as much as a GM.",
    fullDescription: "JJ was the very first DM I'd ever had on Startplaying. I had gotten into TTRPGs on a whim only a few years ago, and naturally got the itch for more.\n\nI landed on JJ almost at random, and it was easily one of the best decisions of my life. That first game of Vampire: The Masquerade opened up a whole new world and gave me some of the best memories I'd had in years. JJ isn't just a DM to me — he's a friend that I hope to have for the rest of my life.\n\nJJ is incredibly knowledgeable and has introduced me to 3 different game systems. His creativity and passion continues to amaze me. He's kind, patient, compassionate, and always willing to listen. He's great at making sure everyone gets their chance to shine, while also making sure things run smoothly.",
    tags: ["Weird West", "Savage Worlds", "Horror", "Adventure"],
    duration: "3.5 hours",
  },
  {
    id: "g10",
    title: "Shifting Sands – Desert Mysteries [Homebrew, Free Session 0]",
    system: "D&D 5e",
    gm: GMS[9],
    dateTime: "2026-04-29T18:00:00",
    totalSeats: 5,
    seatsAvailable: 3,
    pricePerSession: 25,
    shortDescription: "A homebrew desert mystery campaign where the Rule of Cool prevails and your character's story is woven into the world. Free Session 0 included.",
    fullDescription: "Alex and I have played 5E together for almost 10 years, both as a party mate first and later as a dungeon master.\n\nAs good of a PC as he is, Alex shines most brightly as a DM. Wielding creativity as a player with all the freedom afforded to him as a dungeon master, these abilities help him enhance his players' characters as he weaves them into his homebrew worlds.\n\nSome GMs can be extreme rule lawyers — Alex is not one of them. The Rule of Cool usually prevails at his table. For example, he once let a level 11 Way of Shadows monk run up a wall and Superplex a Giant Grick off it while using a bonus action to teleport back to the ground safely. If this doesn't persuade you just how fun of a DM Alex is, you'll just have to book him and find out yourself.",
    tags: ["Homebrew", "Desert", "Mystery", "Rule of Cool", "Free Session 0"],
    duration: "3.5 hours",
  },
  {
    id: "g11",
    title: "Columbia By Night: A Hunter Chronicle",
    system: "Hunter: The Reckoning",
    gm: GMS[10],
    dateTime: "2026-04-30T20:00:00",
    totalSeats: 4,
    seatsAvailable: 1,
    pricePerSession: 15,
    shortDescription: "The streets of Columbia are rife with supernatural threats. Inspired by Stranger Things, Stephen King's IT, and Supernatural — come for the monsters, stay for the people.",
    fullDescription: "The city streets of Columbia are rife with supernatural threats that the average person does their absolute best to avoid every single day.\n\nBut you are not one of those average people. You are someone awakened to the dangers that can plague even your small college city when the things that go bump in the night come a-knocking.\n\nIn Columbia By Night: A Hunter Chronicle, you will adopt the role of a hunter making their way into The World of Darkness. Whether you are a novice to the system or a returning veteran, you can enjoy this dynamic and evolving city of supernatural perils and dangers. Come prepared for a unique character-driven experience inspired by Stranger Things, Kids on Bikes, Stephen King's IT, and Supernatural. Come for the monsters, stay for the people.",
    tags: ["World of Darkness", "Investigation", "Supernatural Horror", "Character Drama"],
    duration: "3 hours",
  },
  {
    id: "g12",
    title: "The Lucky Bastion Presents: Curse of Strahd",
    system: "D&D 5e",
    gm: GMS[11],
    dateTime: "2026-05-01T19:00:00",
    totalSeats: 5,
    seatsAvailable: 1,
    pricePerSession: 15,
    shortDescription: "Enter the mist-shrouded village of Barovia. Children stand in the street, a dark house looms — and the vampire Strahd von Zarovich watches from his castle.",
    fullDescription: "A band of weary travelers hiking a long and treacherous gravel pass through the forest becomes enveloped in mist. The land becomes flat and more like plains than forest, the gravel road leading to a village — its tall houses dark as tombstones.\n\nA soft whimpering draws your eye toward a pair of children standing in the middle of an otherwise lifeless street. 'Please help us — there's a monster in our house, our baby brother is still inside, and our parents are trapped in the basement. Won't you please help us?'\n\nShe then points to a tall brick row house that has seen better days. Its windows are dark. It has a gated portico on the ground floor, and the rusty gate is slightly ajar. The houses on either side are abandoned, their windows and doors boarded up.",
    tags: ["Gothic Horror", "Vampire", "Published Adventure", "Atmosphere"],
    duration: "3.5 hours",
  },
  {
    id: "g13",
    title: "The Module For You",
    system: "D&D 5e",
    gm: GMS[12],
    dateTime: "2026-05-01T14:00:00",
    totalSeats: 5,
    seatsAvailable: 4,
    pricePerSession: 5,
    shortDescription: "A welcoming, relaxed game with clear story and lore, no judgment, and a GM who notices and reacts to every single thing every player does. First game nearly free.",
    fullDescription: "Two friends and I signed up for a free one-shot with less than 24 hours notice and didn't know what to expect — but it was a great time. There was a clear story and lore, so we knew why we were doing what we were doing, and the adventure was well laid out.\n\nBrian was a great roleplayer — he leaned into every player character's unique personality and playstyle. The serious nature of the mission was mixed flawlessly with humor the entire time.\n\nOne thing especially appreciated: Brian noticed and reacted to every little thing done by every player character, no matter how inconsequential. When a character made a quip while others were mid-chat, he made the NPCs react appropriately. No action or statement was ignored, which really improved the experience for everyone. Very relaxed, welcoming, and super fun.",
    tags: ["Beginner Friendly", "Welcoming", "Budget-Friendly", "One-Shot"],
    duration: "3 hours",
  },
  {
    id: "g14",
    title: "Baker's Doesn'ts – A Sweet One-Shot With Teeth",
    system: "D&D 5e",
    gm: GMS[13],
    dateTime: "2026-05-02T19:00:00",
    totalSeats: 4,
    seatsAvailable: 2,
    pricePerSession: 15,
    shortDescription: "A simple, no-fuss one-shot run via DnDBeyond and Discord — no obscure VTT required. Jesse manages the table brilliantly and makes sure everyone's time is respected.",
    fullDescription: "I really enjoyed Jesse's simple approach to maps that lets us get right into it. If I have to learn one more obscure virtual tabletop UI just so my token can show a fireball on screen, I'm gonna eat my shoe. All you need is DnDBeyond.com and Discord. Simple. No degree in computer software necessary.\n\nJesse also does a really good job at managing the table — something I've seen some DMs struggle with. He values everyone's time and keeps things on track and fun. No more listening to arguments about rules for 30 minutes of your paid adventure. He makes a ruling, assures everyone their feelings are valid, and then gets back to questing.\n\nAdditionally you can just tell this guy is having fun, and it's super contagious.",
    tags: ["One-Shot", "Streamlined", "Beginner Friendly", "Humor"],
    duration: "3 hours",
  },
  {
    id: "g15",
    title: "Vecna: Prequel and Eve of Ruin",
    system: "D&D 5e",
    gm: GMS[14],
    dateTime: "2026-05-02T20:00:00",
    totalSeats: 5,
    seatsAvailable: 3,
    pricePerSession: 20,
    shortDescription: "Play in worlds and stories of Christian's own design. 25 years of experience, LGBTQIA+ safe table, and a dynamic world that moves as the players do.",
    fullDescription: "Hello! My name is Christian. I'm here to offer players the opportunity to play in worlds and stories of my own design. I have 25 years of experience, and having been on both sides of the screen, I've taken a great deal of time to learn what it means to be both a good DM AND a good player.\n\nMy games are a good mix of roleplay and combat with a focus on the narrative side of things. The story matters more to me than anything else — my ideal players are interested in building a story alongside me. Players can also look forward to a dynamic world that moves as the players do, and a fun time being challenged by puzzles and riddles.\n\nPart of my promise as a DM is that there is no tolerance for hate. My table is a safe space for LGBTQIA+, BIPOC, and neurodivergent players. I also am beginner friendly and have no problems teaching the game.",
    tags: ["LGBTQIA+ Safe", "Safe Space", "Narrative", "Beginner Friendly"],
    duration: "3.5 hours",
  },
  {
    id: "g16",
    title: "Lancer – Operation Solstice Rain & Winter Scar",
    system: "Lancer",
    gm: GMS[15],
    dateTime: "2026-05-03T13:00:00",
    totalSeats: 4,
    seatsAvailable: 1,
    pricePerSession: 25,
    shortDescription: "Highly tactical mech combat RPG with macros, animated SFX, atmospheric music, and fully voice-acted NPCs. Learn to play in a cinematic science-fiction setting.",
    fullDescription: "As your GM, I'm dedicated to providing an immersive and engaging experience while staying true to the core rules of Lancer.\n\nTactical Combat: Combat will be highly tactical, with a focus on positioning, mech abilities, and teamwork. Rules as written will be followed closely, and I'll make sure to provide guidance. SFX and Macros: I will be using macros and special effects to enrich the environment — grenades will be thrown, core powers animated, cinematic moments enhanced with dramatic music and explosions.\n\nBackground Music and Sound Effects: I'll use atmospheric music and sound effects throughout. Whether it's the hum of your mech's engines or the tension of an incoming attack, music will adjust to match the tone of the moment. Character Voices and NPCs: Each NPC will have their own personality and distinct voice.",
    tags: ["Mech", "Sci-Fi", "Tactical Combat", "Learn to Play"],
    duration: "4 hours",
  },
  {
    id: "g17",
    title: "Buried Secrets of Emberdeep (3-Session Arc)",
    system: "Pathfinder 1e",
    gm: GMS[16],
    dateTime: "2026-05-04T19:00:00",
    totalSeats: 4,
    seatsAvailable: 3,
    pricePerSession: 18,
    shortDescription: "When the earth cracked open at a barley farm, no one expected what lay beneath. An ancient dwarven ruin, a cursed forest, and something waking up below the sinkhole.",
    fullDescription: "When the earth cracked open in the back fields of Garren Feld's Barley Farm, no one expected what lay beneath. At first it was just a sinkhole. But then came the strange lights, the silence of birdsong, and the low droning music that drifted across the valley at dusk.\n\nLivestock vanished. Dreams turned sour. Beneath moss-covered stone and root-choked passageways lie the remnants of Emberdeep — a forgotten mining hold turned shrine, once proud in its worship of Torag and the sacred flame. Its halls are cracked and flooded, littered with rusted tools. But signs of recent movement abound.\n\nThe forest above is no less strange. Paths loop back on themselves. Trees seem to listen. Small, clever things leave offerings — or warnings. This module balances the grit of ancient dwarven ruins with the enchantment and trickery of a wild, living forest. Intended for characters of levels 1–2.",
    tags: ["Dungeon Crawl", "Mystery", "Fey", "Short Arc", "Pathfinder"],
    duration: "3.5 hours",
  },
  {
    id: "g18",
    title: "Crestfallen Prince",
    system: "D&D 5e",
    gm: GMS[17],
    dateTime: "2026-05-05T20:00:00",
    totalSeats: 5,
    seatsAvailable: 4,
    pricePerSession: 15,
    shortDescription: "This is no fairy tale. A sealed prince, an ancient curse, and the same dream haunting each of you — a cracked crown, a voice from the dark, a prince who should never wake.",
    fullDescription: "This is no fairy tale.\n\nLong before the Cataclysm reshaped the world, a prince of immense power was sealed away in the EverDark — not slain, but cursed into an endless sleep by magic older than recorded history. His name has been erased. His kingdom reduced to whispers. The only known entrance to the EverDark lies beneath Iron Keep in Veridia — sealed, guarded, and officially forgotten.\n\nOne night, each of you begins to dream. The same dream. A crown cracked in half. A voice calling from the dark. And a prince who should never wake… yet begs you to come.\n\nDrawn together by fate, prophecy, or curiosity, the party will travel to Veridia to uncover the truth: Why was the prince sealed away? What happens if he wakes? And why you?",
    tags: ["Gothic", "Mystery", "Original Setting", "Dark Fantasy"],
    duration: "3.5 hours",
  },
  {
    id: "g19",
    title: "Lost Mines of Phandelver – New to D&D Friendly",
    system: "D&D 5e",
    gm: GMS[18],
    dateTime: "2026-05-06T14:00:00",
    totalSeats: 5,
    seatsAvailable: 3,
    pricePerSession: 15,
    shortDescription: "The classic D&D starter adventure, run in a laid-back and relaxed environment designed for first-time players. First session is free — try before you buy.",
    fullDescription: "As the game title says, this is a game designed for new players who want to try out D&D for the first time without fear of judgment and in a laid back and relaxed environment.\n\nNestled on the northern Sword Coast is the town of Phandalin. Only in the past few years have settlers built a new village on the ruins of the old. Threatening their efforts are bandits, brigands, and monsters.\n\nYou are a newly self-described adventurer. A good friend, the dwarf Gundren Rockseeker, has tasked you with taking a wagon of merchandise to Phandalin. Sounds like an easy job, right? Well, little do you know your life is about to be turned upside down — rescue missions, dungeon diving, and confronting otherworldly beings await. Do you have the stomach for it?\n\nFirst session is free — try before you buy!",
    tags: ["Beginner Friendly", "Classic Adventure", "Free First Session", "New Player Friendly"],
    duration: "3 hours",
  },
  {
    id: "g20",
    title: "Age of Ashes: Cult of Cinders (Level 6 Entry)",
    system: "D&D 5e",
    gm: GMS[19],
    dateTime: "2026-05-07T18:00:00",
    totalSeats: 5,
    seatsAvailable: 2,
    pricePerSession: 25,
    shortDescription: "Drop into Book 2 of this Pathfinder-converted epic at Level 6. Jungle expeditions, ancient ruins, a draconic cult, and a campaign arc running all the way to Level 20.",
    fullDescription: "Two seats just opened in our Level 6 Age of Ashes (Age of Ashes) 5e campaign, and the timing couldn't be better. The party has stepped through a portal into a deadly jungle, hunting a draconic cult preparing rituals that could burn Golarion to the ground.\n\nYou'll be joining an established group right as Book 2: Cult of Cinders kicks off. Expect jungle expeditions, ancient ruins, dangerous alliances, and a cult that won't go down quietly.\n\nThis is Pathfinder's epic Age of Ashes storyline, fully converted and rebalanced for smooth 5e play — a full campaign arc all the way to Level 20. Players who enjoy teamwork, story-driven play, and bold character choices will thrive here. A full recap and smooth onboarding for your Level 6 character is provided.",
    tags: ["Epic Campaign", "Conversion", "Level 20", "Draconic", "Adventure"],
    duration: "4 hours",
  },
];
